name: .NET (C#)

on:
  push:
    branches: [ "main" ]
    paths: ./csharp
  pull_request:
    branches: [ "main" ]
    paths: ./csharp

jobs:
  build:    
    runs-on: ubuntu-latest
    env:
      working-directory: ./csharp
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{env.working-directory}}
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{env.working-directory}}
